language: python
python:
  - 2.7
# command to install dependencies
before_install:
  - pip install coveralls
install:
  - "pip install ."
script: py.test
  - coverage run --source habakkuk -m py.test
  - coverage report -m
after_success:
  - coveralls
