language: python
python:
  - 2.7
# command to install dependencies
before_install:
  - pip install coveralls
  - pip install codecov
install:
  - "pip install ."
script:
  - coverage run --source=habakkuk -m py.test
  - coverage report -m
after_success:
  - coveralls
  - codecov --token=661f771e-2823-4a07-85ad-4db4516ba4f3
# Configure travis to deploy to the pypi server when a new
# version is tagged on master
deploy:
  provider: pypi
  user: "trackstand"
  password:
    secure: "A9BpeNY9Yvwqs7Z51dLS8OAd4iKvnsIF7t5xO/V5tS3t63xM9I6mC1mYm3TbT8eLAEje78JPXPIIAzLbOiGyaL59h01Qh3jA7AtK7tqTV3zQt5nQf6vKs0Uv1Bep65eTD8eIO7J3IM0nswk8aSeKWBkHO7rwuOOeAAI/aU3XFU0hXkMjpXz8om/crj1tfKvHdJ8X+Bzlslau4X1Q1oW33QJy0c+verHW4Ux/eAV365C6KkhRKCmaU0VHutwtVcplSulq4nvVTYCIoC1NL7wf7eR9LAkzaXAuo1aPcr3Gcw+TfQgxw28+w+jtq+OwEh9HSiw64FyaVl8utotm4hbRLR6xru4qpH2Sm7HzB1VSHS9Oi4REap2c1kxjfV6C7OEVxfrIEHBZVs59VIyg5+qlvSaKJLnNIngEXJu6jdNJFwYAUpViglWR43SaqcErDPbliAD9cdIpibWv2zT6O5gISv/aiPfL4qKINcEEPM6uONb5BWSgvMmLQuQXIsihvvRYtQWqJytqfX7HGm0rjWBWruPMl2WYEuYZ0IldIRREhSNBgryaKp1ikzUgAndMBJstb+CYvy30rMcxJESyVs5vJkwqYkw/vIbvjEsZZ5i2Y8Lh92Jb4XVuaJGUEldnN9e/cJaexuZT8eVbwhon3rBNWTMldGm+eng7u1FQmLEMFJo="
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
